services:
  db:
    image: postgres:16-alpine
    container_name: airline_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-aerolinea_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10

  api:
    build: .
    container_name: airline_fastapi_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/workspace
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/aerolinea_db
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-aerolinea_db}
      - API_V1_PREFIX=/api/v1
    volumes:
      - .:/workspace
    command: ["./scripts/entrypoint.sh"]

volumes:
  postgres_data:
